---
- name: Converge
  hosts: all
  become: true

  vars:
    plugins: "job-dsl"
    jenkins_user: "root"
    jenkins_group: "root"
    jenkins_update_center_url: "http://mirror.xmission.com/jenkins/updates/current/update-center.json"
    jenkins_experimental_update_center_url: "http://mirror.xmission.com/jenkins/updates/experimental/update-center.json"
    jenkins_plugin_info_url: "http://mirror.xmission.com/jenkins/updates/current/plugin-versions.json"

  pre_tasks:
    - include_tasks: jenkins.yml

  roles:
    - role: v1v.jenkins_plugin_cli
