---
- name: Converge
  hosts: all
  become: true

  vars:
    plugins: "job-dsl"
    jenkins_user: "root"
    jenkins_group: "root"
    jenkins_updates_center_url: "http://mirror.xmission.com/jenkins/updates/current/update-center.json"
    jenkins_experimental_updates_center_url: "http://mirror.xmission.com/jenkins/updates/experimental/update-center.json"
    jenkins_plugin_info_url: "http://mirror.xmission.com/jenkins/updates/current/plugin-versions.json"

  pre_tasks:
    - include_tasks: java-8.yml
    - include_tasks: jenkins.yml

  roles:
    - role: geerlingguy.java

  tasks:
    - name: "Include jenkins_plugin_cli"
      include_role:
        name: "jenkins_plugin_cli"
