---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_IMAGE:-adoptopenjdk:8-jre}"
    command: ${MOLECULE_DOCKER_COMMAND:-"bash -c 'while true; do sleep 1; done'"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
